// 坐标说明：统一采用 GCJ-02 [lng, lat]（与高德地图一致），坐标经高德 POI、
// 百科及考古资料核对。线性/面状景点（故黄河、护城河、洪泽湖大堤等）取代表性点位。
export const SPOTS = [
  // 苏轼 · 徐州
  {
    id: "huanglou-park",
    name: "黄楼公园",
    aliases: ["黄楼"],
    city: "徐州",
    characterId: "su-shi-xuzhou",
    address: "江苏省徐州市鼓楼区黄河南路",
    position: [117.1818754, 34.2728792],
    description: "黄楼始建于北宋元丰元年（1078年），是苏轼任徐州知州时率军民抗洪取胜后，在故黄河畔主持修建的纪念建筑，为徐州五大名楼之一。现存黄楼为1988年按宋代规制重建的重檐歇山式仿宋建筑，内藏苏轼兄弟合作碑刻与历代诗文遗迹。",
    images: ["/static/assets/spots/huanglou-1.webp", "/static/assets/spots/huanglou-2.webp"],
  },
  {
    id: "baibu-hong",
    name: "百步洪广场",
    aliases: ["百步洪", "百步洪故址"],
    city: "徐州",
    characterId: "su-shi-xuzhou",
    address: "江苏省徐州市云龙区民主南路207号",
    position: [117.194, 34.251],
    description: "百步洪即“徐州三洪”之一的徐州洪，位于故黄河和平桥至显红岛一带，因河床巨石盘踞、长约百余步而得名。这里曾是古代漕运必经之地，河道狭窄、水流湍急、船行艰难；苏轼在徐州时与苏辙各有咏百步洪的诗篇传世。",
    images: ["/static/assets/spots/baibu-hong-1.webp", "/static/assets/spots/baibu-hong-2.webp"],
  },
  {
    id: "lvliang-hong",
    name: "吕梁洪",
    aliases: ["吕梁", "吕梁风景区"],
    city: "徐州",
    characterId: "su-shi-xuzhou",
    address: "江苏省徐州市铜山区吕梁山风景区",
    position: [117.486741, 34.156741],
    description: "吕梁山风景区位于徐州市铜山区东南二十余公里处，规划面积约186平方公里，为国家AAA级旅游景区，素有“徐州市的后花园”之称。区内山峦起伏、古迹众多，历史上的吕梁洪是“徐州三洪”之一，与百步洪并见于苏轼徐州诗文。",
    images: ["/static/assets/spots/lvliang-hong-1.webp", "/static/assets/spots/lvliang-hong-2.webp"],
  },
  {
    id: "old-yellow-river",
    name: "故黄河·徐州古城水系",
    aliases: ["故黄河", "徐州古城水系", "黄河故道"],
    city: "徐州",
    characterId: "su-shi-xuzhou",
    address: "江苏省徐州市故黄河沿线",
    position: [117.1931842, 34.2678831],
    description: "黄河自南宋建炎二年（1128年）夺泗入淮，至清咸丰五年（1855年）铜瓦厢改道，流经徐州六百余年，留下如今的故黄河，被称为徐州的“母亲河”。故黄河与古泗水、运河水系在徐州交织，既是历史洪患的见证，也塑造了徐州“城下有城”的水城格局。",
    images: ["/static/assets/spots/old-yellow-river-1.webp", "/static/assets/spots/old-yellow-river-2.webp"],
  },
  {
    id: "yanzi-pavilion",
    name: "燕子楼",
    aliases: ["燕子楼公园", "云龙公园"],
    city: "徐州",
    characterId: "su-shi-xuzhou",
    address: "江苏省徐州市云龙区和平路150号",
    position: [117.1727978, 34.255863],
    description: "燕子楼位于云龙公园知春岛上，初建于唐贞元年间，原为武宁节度使张愔为爱妾、女诗人关盼盼所建，因飞檐挑角形如飞燕而得名，为徐州五大名楼之一。现存建筑为1985年重建的双层回廊式仿古建筑，苏轼《永遇乐·彭城夜宿燕子楼》即咏于此。",
    images: ["/static/assets/spots/yanzi-1.webp", "/static/assets/spots/yanzi-2.webp"],
  },
  {
    id: "yunlong-mountain",
    name: "云龙山·放鹤亭",
    aliases: ["云龙山", "放鹤亭"],
    city: "徐州",
    characterId: "su-shi-xuzhou",
    address: "江苏省徐州市云龙区云龙山",
    position: [117.172333, 34.239415],
    description: "放鹤亭位于云龙山第一节山顶，初为北宋隐士张天骥于元丰元年（1078年）所建，张天骥自号“云龙山人”，苏轼《放鹤亭记》使此亭与云龙山闻名于世。现存建筑为明嘉靖后屡经重修的砖木结构、歇山飞檐式厅轩，是“古彭三胜”之一。",
    images: ["/static/assets/spots/yunlong-1.webp", "/static/assets/spots/yunlong-2.webp"],
  },
  {
    id: "xima-tai",
    name: "戏马台",
    aliases: ["户部山"],
    city: "徐州",
    characterId: "su-shi-xuzhou",
    address: "江苏省徐州市云龙区项王路1号",
    position: [117.1841618, 34.2564486],
    description: "戏马台位于徐州户部山（古称南山）最高处，公元前206年项羽灭秦后自立为西楚霸王、定都彭城，在此“因山筑台，以观戏马”，因而得名。它是徐州现存最早的地面古迹之一，素有“西楚第一胜迹”“徐州第一胜迹”之称，现为国家AAAA级旅游景区。",
    images: ["/static/assets/spots/xima-tai-1.webp", "/static/assets/spots/xima-tai-2.webp"],
  },
  {
    id: "kuaizai-pavilion",
    name: "快哉亭",
    aliases: ["快哉亭公园"],
    city: "徐州",
    characterId: "su-shi-xuzhou",
    address: "江苏省徐州市云龙区解放路快哉亭公园",
    position: [117.1882548, 34.2605756],
    description: "快哉亭位于徐州解放路快哉亭公园内，始建于北宋熙宁十年（1077年），由李邦直在唐代阳春亭旧址上改建，苏轼任徐州知州时作《快哉此风赋》为其命名。现存为两层塔楼式仿宋建筑，匾额出自画家李可染之手，是徐州古城名亭之一。",
    images: ["/static/assets/spots/kuaizai-1.webp", "/static/assets/spots/kuaizai-2.webp"],
  },

  // 陈瑄 · 淮安
  {
    id: "qingjiangpu",
    name: "清江浦",
    aliases: ["清江大闸", "陈潘二公祠", "陈瑄二公祠"],
    city: "淮安",
    characterId: "chen-xuan-huaian",
    address: "江苏省淮安市清江浦区里运河畔",
    position: [119.0363, 33.595],
    description: "清江闸又称清江大闸，位于淮安清江浦区里运河航道，始建于明永乐十三年（1415年），由漕运总兵官陈瑄主持建造。它是京杭大运河上保存最为完整的明代古闸之一，2014年作为中国大运河遗产点列入世界文化遗产名录，也是清江浦地名的源头。",
    images: ["/static/assets/spots/qingjiangpu-1.webp", "/static/assets/spots/qingjiangpu-2.webp"],
  },
  {
    id: "li-canal",
    name: "里运河文化长廊",
    aliases: ["里运河"],
    city: "淮安",
    characterId: "chen-xuan-huaian",
    address: "江苏省淮安市清江浦区里运河沿线",
    position: [119.030783, 33.595155],
    description: "里运河文化长廊位于淮安清江浦区，是国家AAAA级旅游景区，涵盖中国大运河清口枢纽、清江大闸两处世界文化遗产点及淮扬运河淮安段遗产河道。它北起大闸口、南至堂子巷，总范围约45平方公里，是展示清江浦漕运与水城文化的重要滨水长廊。",
    images: ["/static/assets/spots/licanal-1.webp", "/static/assets/spots/licanal-2.webp"],
  },
  {
    id: "banzha",
    name: "板闸遗址",
    aliases: ["板闸", "板闸遗址公园"],
    city: "淮安",
    characterId: "chen-xuan-huaian",
    address: "江苏省淮安市淮安区板闸遗址公园",
    position: [119.0986084, 33.5509161],
    description: "板闸遗址位于古淮河与京杭大运河交汇处的淮安，是明清两代淮安段运河沿线的重要历史文化遗存，也是中国大运河入选世界文化遗产名录后的重大考古发现。它见证了淮安段运河六百余年的治水与漕运变迁。",
    images: ["/static/assets/spots/banzha-1.webp", "/static/assets/spots/banzha-2.webp"],
  },
  {
    id: "caoyun-governor",
    name: "漕运总督署遗址",
    aliases: ["漕运总督署", "总督漕运部院遗址"],
    city: "淮安",
    characterId: "chen-xuan-huaian",
    address: "江苏省淮安市淮安区漕运广场",
    position: [119.1393988, 33.5084979],
    description: "漕运总督署遗址又称总督漕运部院遗址，位于淮安老城区中心，是明、清两代统管全国漕运事务的漕运总督官署建筑群。这里曾是中国历史上主管全国漕运的最高机构，规模宏大、布局严谨，现为江苏省文物保护单位。",
    images: ["/static/assets/spots/caoyun-governor-1.webp", "/static/assets/spots/caoyun-governor-2.webp"],
  },
  {
    id: "qingyan-garden",
    name: "清晏园",
    aliases: ["江淮第一园"],
    city: "淮安",
    characterId: "chen-xuan-huaian",
    address: "江苏省淮安市清江浦区人民南路",
    position: [119.0190237, 33.586378],
    description: "清晏园位于淮安清江浦区人民南路西侧，是国家AAAA级旅游景区、全国重点文物保护单位，也是我国治水和漕运史上唯一保存完好的衙署园林，素有“江淮第一园”之称。园内水域开阔、格局疏朗，是苏北地区最具代表性的古典园林。",
    images: ["/static/assets/spots/qingyan-garden-1.webp", "/static/assets/spots/qingyan-garden-2.webp"],
  },
  {
    id: "hexia-town",
    name: "河下古镇",
    aliases: ["河下"],
    city: "淮安",
    characterId: "chen-xuan-huaian",
    address: "江苏省淮安市淮安区河下古镇",
    position: [119.1280918, 33.5288883],
    description: "河下古镇位于淮安区西北隅、古邗沟入淮处的古末口，曾名北辰镇，历史可上溯至春秋末期，约2500年。它是淮安保存最完好的历史街区，现存21条街、91条巷、13家坊，是淮扬菜发源地，也是吴承恩、梁红玉等历史名人的故里。",
    images: ["/static/assets/spots/hexia-town-1.webp", "/static/assets/spots/hexia-town-2.webp"],
  },
  {
    id: "wugong-shrine",
    name: "吴公祠",
    aliases: ["敕建吴勤惠公祠"],
    city: "淮安",
    characterId: "chen-xuan-huaian",
    address: "江苏省淮安市清江浦区轮埠路161号",
    position: [119.035, 33.594],
    description: "陈潘二公祠位于淮安清江浦区里运河畔轮埠路，原名陈公祠，创建于明正统年间，纪念明代首任漕运总兵官、平江伯陈瑄，清乾隆年间加祀治水名臣潘季驯，改称陈潘二公祠。毗邻的吴公祠为清光绪年间为纪念漕运总督吴棠奉旨而建。",
    images: ["/static/assets/spots/wugong-shrine-1.webp", "/static/assets/spots/wugong-shrine-2.webp"],
  },
  {
    id: "zhongzhou-island",
    name: "中洲岛·清江浦楼",
    aliases: ["中洲岛", "清江浦楼"],
    city: "淮安",
    characterId: "chen-xuan-huaian",
    address: "江苏省淮安市清江浦区圩北路与越河街交叉口南侧",
    position: [119.03437, 33.593608],
    description: "清江浦楼位于淮安清江浦景区中洲岛东端，2003年异地重建，高23米，为明三暗五楼阁式仿古建筑，飞檐翘角、三面临水，是清江浦地名的标志。历史上的旧楼建于清雍正七年（1729年），现为淮安市楹联博物馆。",
    images: ["/static/assets/spots/zhongzhou-island-1.webp", "/static/assets/spots/zhongzhou-island-2.webp"],
  },
  {
    id: "huaian-government",
    name: "淮安府署",
    aliases: ["淮安府"],
    city: "淮安",
    characterId: "chen-xuan-huaian",
    address: "江苏省淮安市淮安区东门大街38号",
    position: [119.14037, 33.51254],
    description: "淮安府署始建于明洪武三年（1370年），一直沿用至清末，已有640余年历史，是全国仅存的两座府署之一。它占地五万余平方米，正堂面积超过500平方米，为全国衙署正堂之最，现为全国重点文物保护单位、国家AAAA级旅游景区。",
    images: ["/static/assets/spots/huaian-government-1.webp", "/static/assets/spots/huaian-government-2.webp"],
  },
  {
    id: "hongze-dike",
    name: "洪泽湖大堤·高家堰",
    aliases: ["洪泽湖大堤", "高家堰", "高家长堤"],
    city: "淮安",
    characterId: "chen-xuan-huaian",
    address: "江苏省淮安市洪泽区（北起淮阴区码头镇）",
    position: [118.92416, 33.44227],
    description: "洪泽湖大堤古称高家堰，始建于东汉建安五年（200年），由广陵太守陈登主持修筑，北起码头镇、南至蒋坝，全长70余公里，是仅次于都江堰的国内第二大古堰，也是世界上最古老的大型有坝引水工程之一，2014年列入世界文化遗产。",
    images: ["/static/assets/spots/hongze-dike-1.webp", "/static/assets/spots/hongze-dike-2.webp"],
  },

  // 张伯行 · 苏州
  {
    id: "baodai-bridge",
    name: "宝带桥",
    aliases: ["宝带"],
    city: "苏州",
    characterId: "zhang-boxing-suzhou",
    address: "江苏省苏州市吴中区宝南路北端",
    position: [120.6495001, 31.2587712],
    description: "宝带桥始建于唐元和年间（816—819年），由苏州刺史王仲舒主持建造，因他带头捐出宝带以筹资金而得名。它是中国现存最长的古代联拱石桥，全长约317米、53孔薄墩连拱，与赵州桥等并列为中国四大古桥，2001年被列为全国重点文物保护单位，也是大运河苏州段的标志性地标。",
    images: ["/static/assets/spots/baodai-1.webp", "/static/assets/spots/baodai-2.webp"],
  },
  {
    id: "shantang-street",
    name: "山塘街",
    aliases: ["山塘", "白公堤", "山塘河"],
    city: "苏州",
    characterId: "zhang-boxing-suzhou",
    address: "江苏省苏州市姑苏区山塘街",
    position: [120.5979854, 31.3193291],
    description: "山塘街又称“七里山塘”，位于苏州古城西北，东起阊门、西接虎丘，全长约七华里，是唐代诗人白居易任苏州刺史时主持修筑的水街。它一头连着繁华阊门、一头连着虎丘，集街河、市集与运河文化于一体，现为中国历史文化名街、国家AAAA级景区，并列入大运河世界文化遗产。",
    images: ["/static/assets/spots/shantang-1.webp", "/static/assets/spots/shantang-2.webp"],
  },
  {
    id: "pingjiang-road",
    name: "平江路",
    aliases: ["平江河道"],
    city: "苏州",
    characterId: "zhang-boxing-suzhou",
    address: "江苏省苏州市姑苏区平江路",
    position: [120.6296912, 31.3149294],
    description: "平江路是苏州姑苏区东北部沿平江河而建的历史老街，北起东北街、南至干将东路，全长1606米。平江历史街区是苏州古城迄今保存最为完整的区域，基本延续了南宋《平江图》以来的水巷格局，被誉为“古城缩影”，2009年入选首批中国十大历史文化名街。",
    images: ["/static/assets/spots/pingjiang-1.webp", "/static/assets/spots/pingjiang-2.webp"],
  },
  {
    id: "canglang-pavilion",
    name: "沧浪亭",
    aliases: ["沧浪"],
    city: "苏州",
    characterId: "zhang-boxing-suzhou",
    address: "江苏省苏州市姑苏区沧浪亭街3号",
    position: [120.6214474, 31.296731],
    description: "沧浪亭位于苏州城南三元坊，始建于北宋庆历年间，是苏州现存历史最悠久的古典园林，也是现存最早的文人园林之一。原为五代吴越国孙承祐的池馆，北宋诗人苏舜钦购得后傍水建亭，取“沧浪之水清兮，可以濯吾缨”之意命名，与狮子林、拙政园、留园并称苏州宋、元、明、清四大园林。",
    images: ["/static/assets/spots/canglang-1.webp", "/static/assets/spots/canglang-2.webp"],
  },
  {
    id: "xunfu-yamen",
    name: "江苏巡抚衙门旧址",
    aliases: ["巡抚衙门旧址", "书院巷"],
    city: "苏州",
    characterId: "zhang-boxing-suzhou",
    address: "江苏省苏州市姑苏区书院巷20号",
    position: [120.6177386, 31.299801],
    description: "江苏巡抚衙门旧址位于苏州姑苏区书院巷20号，原为鹤山书院所在地。明宣德五年（1430年）置应天巡抚、此处为巡抚行台，清代更名江苏巡抚衙门；现存建筑为同治五年（1866年）重建，中轴线上存头门、仪门、后堂、后楼四进，现为江苏省文物保护单位，也是张伯行任江苏巡抚时的任职机构所在。",
    images: ["/static/assets/spots/xunfu-yamen-1.webp", "/static/assets/spots/xunfu-yamen-2.webp"],
  },
  {
    id: "panmen",
    name: "盘门",
    aliases: ["盘门景区"],
    city: "苏州",
    characterId: "zhang-boxing-suzhou",
    address: "江苏省苏州市姑苏区盘门景区",
    position: [120.6119542, 31.2895554],
    description: "盘门古称蟠门，位于苏州古城西南隅，是春秋吴国都城“吴都八门”之一，也是全国现存唯一保留完整的水陆并列古城门。其总体布局基本保持元末明初旧观，由水陆城门、瓮城、城楼及两侧城墙构成，素有“北看长城之雄，南看盘门之秀”之说，为全国重点文物保护单位。",
    images: ["/static/assets/spots/panmen-1.webp", "/static/assets/spots/panmen-2.webp"],
  },
  {
    id: "xumen",
    name: "胥门",
    aliases: ["胥门"],
    city: "苏州",
    characterId: "zhang-boxing-suzhou",
    address: "江苏省苏州市姑苏区胥门",
    position: [120.6083074, 31.2995346],
    description: "胥门又名姑胥门，位于苏州城西万年桥南，为春秋吴国建造都城时所辟“八门”之一，因遥对姑胥山（姑苏山）而得名。现存陆门主体为元至正十一年（1351年）重建，历经明清重修，现为江苏省文物保护单位，紧邻护城河。",
    images: ["/static/assets/spots/xumen-1.webp", "/static/assets/spots/xumen-2.webp"],
  },
  {
    id: "fengqiao-hanshan",
    name: "枫桥·寒山寺",
    aliases: ["枫桥", "寒山寺"],
    city: "苏州",
    characterId: "zhang-boxing-suzhou",
    address: "江苏省苏州市姑苏区寒山寺弄24号",
    position: [120.5642846, 31.3125175],
    description: "寒山寺位于苏州阊门外、京杭大运河畔，始建于南朝梁天监年间（502—519年），初名“妙利普明塔院”，唐代更名寒山寺。寺旁的枫桥因唐代诗人张继《枫桥夜泊》而名满天下，运河、古寺与古桥共同构成苏州最具诗意的水乡意象。",
    images: ["/static/assets/spots/fengqiao-hanshan-1.webp", "/static/assets/spots/fengqiao-hanshan-2.webp"],
  },
  {
    id: "huqiu",
    name: "虎丘",
    aliases: ["虎丘山"],
    city: "苏州",
    characterId: "zhang-boxing-suzhou",
    address: "江苏省苏州市姑苏区虎丘山门内8号",
    position: [120.5763549, 31.3379949],
    description: "虎丘又称海涌山，位于苏州古城西北，人文历史可上溯两千五百年，海拔约34米、占地约20公顷，素有“吴中第一名胜”之称。山巅的虎丘塔（云岩寺塔）是苏州的重要地标，山小景多、古迹密集，苏轼曾言“到苏州不游虎丘，乃憾事也”。",
    images: ["/static/assets/spots/huqiu-1.webp", "/static/assets/spots/huqiu-2.webp"],
  },
  {
    id: "suzhou-moat",
    name: "苏州护城河",
    aliases: ["环城河"],
    city: "苏州",
    characterId: "zhang-boxing-suzhou",
    address: "江苏省苏州市古城护城河",
    position: [120.6343061, 31.3118517],
    description: "苏州护城河又称环城河、环古城河，相传为公元前514年吴王阖闾命伍子胥筑阖闾城时所开凿，总长约15.5公里，串联平门、相门、盘门、胥门、阊门等八座古城门和二十余座古桥，是大运河苏州段的重要组成部分，也是2500年古城水城格局的集中体现。",
    images: ["/static/assets/spots/suzhou-moat-1.webp", "/static/assets/spots/suzhou-moat-2.webp"],
  },
];

export function detectSpot(text, characterId) {
  if (!text) return null;
  const candidates = SPOTS.filter((spot) => spot.characterId === characterId);
  return (
    candidates.find((spot) =>
      [spot.name, ...(spot.aliases || [])].some((keyword) => text.includes(keyword))
    ) || null
  );
}
